name = "likes-tracker-worker"
main = "src/worker.js"
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "likes-tracker-db"
database_id = "" # This will be filled in after creating the database

# Environment variables (optional)
[env.production]
# Add any production-specific environment variables here

[env.staging]
# Add any staging-specific environment variables here